booking_project/urls.py
from django.contrib import admin
from django.urls import path
from booking import views

urlpatterns = [
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
    path('time-slots/', views.show_time_slots, name='show_time_slots'),
    path('make-booking/', views.make_booking, name='make_booking'),
    path('edit-booking/<int:pk>/', views.BookingUpdateView.as_view(), name= 'edit-booking'),
    path('booking-success/', views.booking_success, name='booking_success'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'), 
    path('logout/', views.user_logout, name='user_logout'),
    path('cancel-booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('user-bookings/', views.user_bookings, name='user_bookings'),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    email_address = models.EmailField(blank=True, null=True)

    def __str__(self):
        return self.user.username

class TimeSlot(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    max_bookings = models.IntegerField(default=1)  # Max bookings for timeslot
    available = models.BooleanField(default=True)

    @classmethod
    def available_time_slots(cls, user):
        user_bookings = Booking.objects.filter(user=user).values_list('time_slot', flat=True)
        return cls.objects.filter(available=True).exclude(id__in=user_bookings)

    def available_slots(self):
        """
        Spots for timeslot
        """
        booked_slots = self.booking_set.count()
        available_slots = self.max_bookings - booked_slots
        return available_slots

    def __str__(self):
        return f"{self.start_time.strftime('%Y-%m-%d %H:%M')} to {self.end_time.strftime('%Y-%m-%d %H:%M')}"

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_slot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE)
    booking_time = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(blank=True)

booking/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Booking, TimeSlot

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
        'password_too_similar_to_username': "Password is too similar to the username."
    }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__iexact=username).exists():
            raise ValidationError("Username already exists.", code='unique')
        return username

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password1 = cleaned_data.get('password1')

        if password1 and username and password1.lower().startswith(username.lower()):
            raise ValidationError(
                self.error_messages['password_too_similar_to_username'],
                code='password_too_similar_to_username',
            )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['time_slot', 'comments']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        available_time_slots = TimeSlot.objects.filter(booking__isnull=True)
        
        self.fields['time_slot'].queryset = available_time_slots

booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .forms import BookingForm, RegistrationForm
from .models import TimeSlot, Booking
from django.contrib.auth import authenticate
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import Http404
from django.db.models import Q


class BookingUpdateView(UpdateView):
    model = Booking
    fields = ['time_slot', 'comments']
    template_name = 'booking/edit_booking.html'
    success_url = reverse_lazy('user_bookings')

    # Control that the booking is the users
    def dispatch(self, request, *args, **kwargs):
        booking = self.get_object()
        if booking.user != request.user:
            raise Http404("You are not allowed to edit this booking.")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        available_time_slots = TimeSlot.objects.filter(available=True).exclude(booking__user=self.request.user)
        context['available_time_slots'] = available_time_slots
        return context


def main(request):
    return render(request, 'booking/main.html')

def show_time_slots(request):
    time_slots = TimeSlot.objects.all()
    return render(request, 'booking/make_booking.html', {'form': BookingForm(), 'time_slots': time_slots})

@login_required
def make_booking(request):
    
    user_bookings = Booking.objects.filter(user=request.user).values_list('time_slot', flat=True)

    other_users_bookings = Booking.objects.exclude(user=request.user).values_list('time_slot', flat=True)

    booked_time_slots = list(user_bookings) + list(other_users_bookings)

    available_time_slots = TimeSlot.objects.filter(available=True).exclude(id__in=booked_time_slots)

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.save()
            return redirect('booking_success')
    else:
        form = BookingForm()

    return render(request, 'booking/make_booking.html', {'form': form, 'time_slots': available_time_slots})

def booking_success(request):
    return render(request, 'booking/booking_success.html')

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('make_booking')
        else:
            print(form.errors)
    else:
        form = RegistrationForm()
    return render(request, 'booking/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('make_booking')
            else:
                # Handle invalid credentials
                # You might want to display an error message
                pass
    else:
        form = AuthenticationForm()
    return render(request, 'booking/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('main')

@login_required
def cancel_booking(request, booking_id):
    booking = get_object_or_404(Booking, pk=booking_id)
    if request.method == 'POST':
        booking.delete()
        return redirect('user_bookings')
    return render(request, 'booking/cancel_booking.html', {'booking': booking})

@login_required
def user_bookings(request):
    user_bookings = Booking.objects.filter(user=request.user)
    return render(request, 'booking/user_bookings.html', {'user_bookings': user_bookings})

booking/templates/booking/booking_success.html
{% extends "booking/header.html" %}

{% block content %}
    <div class="container">
        <div class="booking-successful">
            <h1>Booking Successful</h1>
            <p>Click <a href="{% url 'user_bookings' %}">here</a> to view and manage your bookings.</p>
        </div>
    </div>
{% endblock content %}

booking/templates/booking/cancel_booking.html
{% extends "booking/header.html" %}
{% block content %}

<div class="center-container">
    <div class="transparent-box">
        <h1>Confirm Cancellation</h1>
        <p>Are you sure you want to cancel your booking for {{ booking.time_slot }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark">Yes, Cancel</button>
        </form>
    </div>
</div>

{% endblock content %}

booking/templates/booking/edit_booking.html
{% extends "booking/header.html" %}
{% block content %}

<div class="center-container">
    <div class="transparent-box">
        <h1>Edit Booking</h1>
        <form method="POST" action="{% url 'edit-booking' booking.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="current_time_slot">Current Time Slot:</label>
                <input type="text" id="current_time_slot" value="{{ booking.time_slot.start_time }} - {{ booking.time_slot.end_time }}" readonly>
            </div>
            <div class="form-group">
                <label for="new_time_slot">Choose New Time Slot:</label>
                <select name="time_slot" id="new_time_slot" class="form-control">
                    {% for time_slot in available_time_slots %}
                        <option value="{{ time_slot.id }}">{{ time_slot.start_time }} - {{ time_slot.end_time }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="id_comments">Comments:</label>
                <textarea name="comments" id="id_comments" class="form-control no-resize">{{ booking.comments }}</textarea>
            </div>
            <button type="submit" class="btn btn-success">Save Changes</button>
            <a href="{% url 'user_bookings' %}" class="btn btn-primary">Bookings</a>
        </form>
    </div>
</div>
{% endblock content %}

booking/templates/booking/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Discgolf Booking System</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <header id="header" class="d-flex justify-content-between align-items-center py-3 px-4">
        <a href="/" id="logo" class="header-content">Discgolf Booking</a>
        <div class="user-info">
            {% if user.is_authenticated %}
                <span class="logged-in-as">Logged in as: {{ user.username }}</span>
            {% endif %}
        </div>
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                Menu
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'user_logout' %}">Log out</a></li>
                    <li><a class="dropdown-item" href="{% url 'user_bookings' %}">Bookings</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'login' %}">Log in</a></li>
                    <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </header>

    <main> 
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer">
        <div class="footer-container">
            <ul id="social">
                <li>
                    <a href="https://www.facebook.com/" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)">
                        <i class="fa-brands fa-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="https://www.instagram.com/" target="_blank" rel="noopener" aria-label="Visit our Instagram page (opens in a new tab)">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                </li>
                <li>
                    <a href="mailto:dummymail@test.test" aria-label="Contact me via email">
                        <i class="fa-regular fa-envelope"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>

<!-- JavaScript code for automatic logout -->
<script>
    // Set the timeout duration (5 minutes in milliseconds)
    var timeoutDuration = 5 * 60 * 1000; // 5 minutes

    // Set the logout function
    var logout = function() {
        window.location.href = "{% url 'user_logout' %}";
    };

    // Set the timeout
    var timeout = setTimeout(logout, timeoutDuration);

    // Reset the timeout on user interaction
    document.addEventListener("mousemove", function() {
        clearTimeout(timeout);
        timeout = setTimeout(logout, timeoutDuration);
    });
</script>

    <!---font awesome-->
    <script src="https://kit.fontawesome.com/f1f83dc3cf.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

booking/templates/booking/login.html
{% extends "booking/header.html" %}
{% block content %}

<div class="login-container">
    <h2>Login</h2>
    <hr>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>

        <button type="submit">Log in</button>
    </form>
</div>

{% endblock content %}

booking/templates/booking/main.html
{% extends "booking/header.html" %}
{% block content %}

    <div class="info-box">
        <h2>Welcome to Disc Golf Booking</h2>
        <p>Here you can book time slots to play disc golf at our beautiful course.</p>
        <p>Our course offers a challenging yet enjoyable experience for players of all skill levels.</p>
        <p>Our course is nestled in the heart of nature, surrounded by lush greenery and towering trees, providing a serene and picturesque setting for your disc golf experience.</p>
        <p>With its diverse terrain and strategically placed baskets, our course offers a dynamic and engaging challenge for players of all skill levels. Whether you're a seasoned pro or new to the game, you'll find something to enjoy on our course.</p>
        <p>Each hole presents its own unique obstacles and opportunities, requiring precision, strategy, and a touch of finesse to navigate successfully. From narrow fairways to tricky doglegs, our course will test your skills and keep you coming back for more.</p>
        <p>So gather your friends, grab your discs, and come experience the thrill of disc golf at our course. We look forward to seeing you on the fairways!</p>
    </div>

{% endblock content %}

booking/templates/booking/make_booking.html
{% extends "booking/header.html" %}
{% block content %}
<div class="center-container">
    <div class="transparent-box">
        <h1>Make Time for some fun</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_time_slot">Time Slots:</label>
                <select name="time_slot" id="id_time_slot" class="form-control">
                    {% for time_slot in time_slots %}
                        <option value="{{ time_slot.id }}">{{ time_slot.start_time }} - {{ time_slot.end_time }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="id_comments">Comments:</label>
                <textarea name="comments" id="id_comments" class="form-control no-resize"></textarea>
            </div>
            <button type="submit" class="btn btn-light">Submit</button>
            <a href="{% url 'user_bookings' %}" class="btn btn-light">Bookings</a>
        </form>
    </div>
</div>
{% endblock content %}

booking/templates/booking/register.html
{% extends "booking/header.html" %}
{% block content %}

<div class="registration-container">
    <h2>Register</h2>
    <hr>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
            {% for error in form.username.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}
            {{ form.email }}
            {% for error in form.email.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
            {% for error in form.password1.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
            {% for error in form.password2.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>

        <button type="submit">Register</button>
    </form>
</div>

{% endblock content %}

booking/templates/booking/user_bookings.html
{% extends "booking/header.html" %}
{% block content %}
<main>
    <div class="center-container">
        <div class="booking-info-box">
            <h2>Booked times</h2>
            {% if user_bookings %}
                {% for booking in user_bookings %}
                    <div class="booking-item">
                        <p>{{ booking.time_slot }}</p>
                        <p>{{ booking.comments }}</p>
                        <div class="action-buttons">
                            <a href="{% url 'edit-booking' booking.id %}" class="btn btn-primary">Change</a>
                            <a href="{% url 'cancel_booking' booking.id %}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>You have no booked times.</p>
            {% endif %}
            
            <div class="make-booking-button">
                <a href="{% url 'make_booking' %}" class="btn btn-success">Make a Booking</a>
            </div>
        </div>
    </div>
</main>
{% endblock content %}